# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=2.0.0
group=com.lonkachu.stackable
java_version=21

# Common
minecraft_version=1.21.8
mod_name=Stackable
mod_author=Lonkachu
mod_id=stackable
license=CC0-1.0
credits=
description=# Stackable\n\nStackable is a mod that increases all block stacking limits to any value less than 2.147B for minecraft 1.21+
minecraft_version_range=[1.21.8, 1.22)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.8-20250717.133445
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.8
parchment_version=2025.07.18

# Fabric
fabric_version=0.132.0+1.21.8
fabric_loader_version=0.17.2

# Forge
forge_version=58.0.10
forge_loader_version_range=[58,)

# NeoForge
neoforge_version=21.8.39
neoforge_loader_version_range=[5,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
