# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=2.1.1
group=com.lonkachu.stackable
java_version=25

# Common
minecraft_version=26.2
fabric_minecraft_version=26.2

mod_name=Stackable
mod_author=Lonkachu
mod_id=stackable
license=CC0-1.0
credits=
description=# Stackable\n\nStackable is a mod that increases all block stacking limits to any value less than 2.147B for minecraft 1.21+
minecraft_version_range=[26.2, 26.3)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-1

# Fabric
fabric_version=0.152.1+26.2
fabric_loader_version=0.19.3

# Forge
forge_version=65.0.0

forge_loader_version_range=[59,)

# NeoForge
neoforge_version=26.2.0.1-beta
neoforge_loader_version_range=[5,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
