# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Get Stackable Version
        uses: madhead/read-java-properties@latest
        id: version
        with: 
          file: gradle.properties
          property: version
          default: 0.0.1

      - name: Get Minecraft Version
        uses: madhead/read-java-properties@latest
        id: mc_version
        with: 
          file: gradle.properties
          property: minecraft_version
          default: 1.0.0

      - name: Get Fabric Version
        uses: madhead/read-java-properties@latest
        id: fabric_version
        with:
         file: gradle.properties
         property: fabric_version
         default: 1.0.0

      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build

      - name: build jarJar so forge doesn't break
        run: ./gradlew jarJar
      - name: cleanup Forge bin
        run: |
          rm forge/build/libs/Stackable-forge-${{ steps.mc_version.outputs.value }}-${{ steps.version.outputs.value }}.jar
          mv forge/build/libs/Stackable-forge-${{ steps.mc_version.outputs.value }}-${{ steps.version.outputs.value }}-all.jar forge/build/libs/Stackable-forge-${{ steps.mc_version.outputs.value }}-${{ steps.version.outputs.value }}.jar

      - name: Save Fabric artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Fabric
          path: fabric/build/libs/
      - name: Save Forge artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Forge
          path: forge/build/libs/
      - name: Save NeoForge artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Neoforge
          path: neoforge/build/libs/

      - name: Publish Fabric
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          #Modrinth + Curse
          modrinth-id: Bc74RbD1
          curseforge-id: 857801
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          name: "[Fabric] Stackable ${{ steps.mc_version.outputs.value }}+${{ steps.version.outputs.value }}"

          loaders: |
            fabric

          files: |
            fabric/build/libs/stackable-fabric-${{ steps.mc_version.outputs.value }}-${{ steps.version.outputs.value }}.jar

          game-versions: |
            [${{ steps.mc_version.outputs.value }}, 1.21.2)

          dependencies:
            fabric@${{ steps.fabric_version }}(required){modrinth:P7dR8mSH}{curseforge:306612}#(ignore:github)

          changelog-file: CHANGELOG.md

      - name: Publish NeoForge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          #Modrinth + Curse
          modrinth-id: Bc74RbD1
          curseforge-id: 857801
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          name: "[NeoForge] Stackable ${{ steps.mc_version.outputs.value }}+${{ steps.version.outputs.value }}"

          loaders: |
            neoforge

          files: |
            neoforge/build/libs/stackable-neoforge-${{ steps.mc_version.outputs.value }}-${{ steps.version.outputs.value }}.jar

          game-versions: |
            [${{ steps.mc_version.outputs.value }}, 1.21.2)

          changelog-file: CHANGELOG.md

      - name: Publish Forge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          #Modrinth + Curse
          modrinth-id: Bc74RbD1
          curseforge-id: 857801
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          name: "[LegacyForge] Stackable ${{ steps.mc_version.outputs.value }}+${{ steps.version.outputs.value }}"

          loaders: |
            forge

          files: |
            forge/build/libs/Stackable-forge-${{ steps.mc_version.outputs.value }}-${{ steps.version.outputs.value }}.jar

          game-versions: |
            [${{ steps.mc_version.outputs.value }}, 1.21.2)

          dependencies:
            fabric@${{ steps.fabric_version }}(required){modrinth:P7dR8mSH}{curseforge:306612}#(ignore:github)

          changelog-file: CHANGELOG.md

      - name: Publish Github
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          #Modrinth + Curse
          github-token: ${{ secrets.GITHUB_TOKEN }}

          name: "Stackable ${{ steps.mc_version.outputs.value }}+${{ steps.version.outputs.value }}"

          loaders: |
            fabric
            neoforge
            forge

          files: |
            fabric/build/libs/stackable-fabric-${{ steps.mc_version.outputs.value }}-${{ steps.version.outputs.value }}.jar
            neoforge/build/libs/stackable-neoforge-${{ steps.mc_version.outputs.value }}-${{ steps.version.outputs.value }}.jar
            forge/build/libs/Stackable-forge-${{ steps.mc_version.outputs.value }}-${{ steps.version.outputs.value }}.jar

          game-versions: |
            [${{ steps.mc_version.outputs.value }}, 1.21.2)

          dependencies:
            fabric@${{ steps.fabric_version }}(required){modrinth:P7dR8mSH}{curseforge:306612}#(ignore:github)

          changelog-file: CHANGELOG.md
